#Special configuration file to run tests on Travis-CI via GitHub notifications
#See http://travis-ci.org/ for details
#
#Note when testing Python 3, the 'python' command will invoke Python 3
#and similarly for PyPy too.

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install biopython
  - ./fetch_sample_data.sh

script:
  - python tests/test_consistency.py
  - python tests/test_scripts.py
